name: ipython-notebook
dependencies:
  - notebook=4
  - ipywidgets
  - ipython=5
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pgcontents=0.5.1
