name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # bind tornado version (websocket problems)
  - tornado = 4.5
  - gensim
 # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pgcontents
