name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 4
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - git+git://github.com/pl31/pgcontents.git
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
